name: CI with Unit Tests and Notifications

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting with flake8
        run: |
          flake8 --exclude=venv

      - name: Format code with black
        run: |
          black . --exclude=venv --check

      - name: Run unit tests with pytest
        run: |
          pytest -v --tb=short

      - name: Generate test coverage report
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report -m

  notify-success:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Discord Success Notification
        if: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            ✅ **Build Successful** on `${{ github.repository }}`
            **Branch:** `${{ github.ref_name }}`
            **Commit:** [`${{ github.sha }}`](${{ github.event.head_commit.url }})
            **Author:** ${{ github.event.head_commit.author.name }}
            **Message:** ${{ github.event.head_commit.message }}

            All tests passed! 🎉

      - name: Slack Success Notification
        if: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#dev'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-failure:
    needs: test
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Discord Failure Notification
        if: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            ❌ **Build Failed** on `${{ github.repository }}`
            **Branch:** `${{ github.ref_name }}`
            **Commit:** [`${{ github.sha }}`](${{ github.event.head_commit.url }})
            **Author:** ${{ github.event.head_commit.author.name }}
            **Message:** ${{ github.event.head_commit.message }}

            Please check the workflow logs for details.

      - name: Slack Failure Notification
        if: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#dev'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-notification:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Discord Deployment Notification
        if: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🚀 **Deployment Ready** for `${{ github.repository }}`
            **Branch:** `main`
            **Commit:** [`${{ github.sha }}`](${{ github.event.head_commit.url }})
            **Author:** ${{ github.event.head_commit.author.name }}

            Ready for production deployment! 🌟

      - name: Slack Deployment Notification
        if: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#deployments'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: |
            🚀 Main branch updated! Ready for deployment.
            Commit: ${{ github.sha }}
            Author: ${{ github.event.head_commit.author.name }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}