name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install and run flake8 lint
        run: |
          pip install flake8
          flake8 --exclude=venv

      - name: Black Code Formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose --exclude=venv"

      - name: Run unit tests
        run: |
          pytest -v --tb=short
